[env:black_F407ZG]
platform = ststm32
platform_packages = framework-arduinoststm32@4.20600, framework-cmsis@2.50700
framework = arduino
board = black_f407zg
lib_deps = stm32duino/STM32duino RTC @ 1.2.0, greiman/SdFat
board_build.core = stm32
build_flags = -DUSE_LIBDIVIDE -std=gnu++11 -UBOARD_MAX_IO_PINS -DUSE_SPI_EEPROM=PE1 -DENABLE_HWSERIAL2 -DENABLE_HWSERIAL3 -DUSBCON -DHAL_PCD_MODULE_ENABLED -DUSBD_USE_CDC -DHAL_CAN_MODULE_ENABLED -DSERIAL_TX_BUFFER_SIZE=128 -DSERIAL_RX_BUFFER_SIZE=128
upload_protocol = dfu
debug_tool = stlink
monitor_speed = 115200

[platformio]
src_dir=speeduino
default_envs = black_F407ZG
